site_name: Ferasdour's site
theme: mkdocs
repo_url: https://github.com/ferasdour/ferasdour.github.io
docs_dir: Docs
copyright: feemcotech
use_directory_urls: true
nav:
  - index.md
plugins:
  - autorefs
  - autolinks
  - glightbox
  - pub-obsidian:
     obsidian_dir: Docs/.obsidian
     templates_dir: Docs/_templates
     img_lazy_loading: true
     backlinks:
      enabled: false
     callouts:
      enabled: true
      indentation: spaces
     links:
      wikilinks_enabled: true
  - search
  - pub-debugger
  - pub-blog
  - pub-social
  - pub-meta
  - pub-minifier
